language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - g++-7
            - gcc-7
            - cmake

compiler:
  - gcc-7
before_script:
  - mkdir Release
  - cd Release
  - cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=Release
script:
  - make
  - ctest openset-unit-test
