language: cpp
compiler:
  - gcc-7
before_script:
  - mkdir Release
  - cd Release
  - cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=Release
script:
  - make
  - ctest openset-unit-test
