os: Visual Studio 2017
platform: x64

environment:

  MSVC_DEFAULT_OPTIONS: OFF

  matrix:
    # - GENERATOR: "Ninja"
    #  CONFIG: Debug
    #  configuration: Debug

    - GENERATOR: "Ninja"
      CONFIG: Release
      configuration: Release

install:
  - git submodule update --init --recursive

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIG%

build:
  project: build\openset.sln # path to Visual Studio solution or project
  parallel: true            # enable MSBuild parallel builds
  verbosity: normal         # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd build
  - ctest -C %CONFIG% -R openset-unit-test