os: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Ninja"
      CONFIG: Debug

    - GENERATOR: "Ninja"
      CONFIG: Release

install:
  - git submodule update --init --recursive

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %CONFIG%
  - cd %CONFIG%
  - cmake .. -DCMAKE_BUILD_TYPE=%CONFIG%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd %CONFIG%
  - ctest -R openset-unit-test