os: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Ninja"
      CONFIG: Debug

    - GENERATOR: "Ninja"
      CONFIG: Release

install:
  - git submodule update --init --recursive

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %CONFIG%
  - cd %CONFIG%
  - cmake .. -DCMAKE_BUILD_TYPE=%CONFIG%

build:
  project: %CONFIG%\openset.sln # path to Visual Studio solution or project
  parallel: true            # enable MSBuild parallel builds
  verbosity: normal         # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd %CONFIG%
  - ctest -R openset-unit-test