environment:
  matrix:
    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

build_script:
  - mkdir %CONFIG%
  - cd %CONFIG%
  - cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=%CONFIG%

test_script:
  - ps: cd _builds
  - ctest -R openset-unit-test